#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v10
# autospec commit: 5905be9
#
Name     : perl-Curses
Version  : 1.45
Release  : 39
URL      : https://cpan.metacpan.org/authors/id/G/GI/GIRAFFED/Curses-1.45.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/G/GI/GIRAFFED/Curses-1.45.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : GPL-1.0
Requires: perl-Curses-license = %{version}-%{release}
Requires: perl-Curses-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : pkgconfig(ncursesw)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The Curses Perl Module
============================================================
COPYRIGHT AND LICENSE INFORMATION IS AT THE END OF THIS FILE
============================================================

%package dev
Summary: dev components for the perl-Curses package.
Group: Development
Provides: perl-Curses-devel = %{version}-%{release}
Requires: perl-Curses = %{version}-%{release}

%description dev
dev components for the perl-Curses package.


%package license
Summary: license components for the perl-Curses package.
Group: Default

%description license
license components for the perl-Curses package.


%package perl
Summary: perl components for the perl-Curses package.
Group: Default
Requires: perl-Curses = %{version}-%{release}

%description perl
perl components for the perl-Curses package.


%prep
%setup -q -n Curses-1.45
cd %{_builddir}/Curses-1.45
pushd ..
cp -a Curses-1.45 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Curses
cp %{_builddir}/Curses-%{version}/Copying %{buildroot}/usr/share/package-licenses/perl-Curses/c0bf1a619a3a61a05da7ec8a9845e48fa4511c97 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Curses.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Curses/c0bf1a619a3a61a05da7ec8a9845e48fa4511c97

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
